In [1]:
import pandas as pd

D = pd.read_csv("people-100.csv")
D.iloc[: -1]
print(D.isnull().sum())

Index            0
User Id          0
First Name       0
Last Name        0
Sex              2
Email            0
Phone            0
Date of birth    1
Job Title        0
dtype: int64


In [2]:
import pandas as pd
import numpy as np

df=pd.read_csv('emp.csv')
print(df.head(15))


   First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0     Douglas    Male    8/6/1993        12:42 PM   97308    6.945   
1      Thomas    Male   3/31/1996         6:53 AM   61933    4.170   
2       Maria  Female   4/23/1993        11:17 AM  130590   11.858   
3       Jerry    Male    3/4/2005         1:00 PM  138705    9.340   
4       Larry    Male   1/24/1998         4:47 PM  101004    1.389   
5      Dennis    Male   4/18/1987         1:35 AM  115163   10.125   
6        Ruby  Female   8/17/1987         4:20 PM   65476   10.012   
7         NaN  Female   7/20/2015        10:43 AM   45906   11.598   
8      Angela  Female  11/22/2005         6:29 AM   95570   18.523   
9     Frances  Female    8/8/2002         6:51 AM  139852    7.524   
10     Louise  Female   8/12/1980         9:01 AM   63241   15.132   
11      Julie  Female  10/26/1997         3:19 PM  102508   12.637   
12    Brandon    Male   12/1/1980         1:08 AM  112807   17.492   
13       Gary    Mal

In [3]:
df.isnull().sum() # no. of each null values in each column
df.isnull().sum().sum()#  total no. of M valuesb

322

In [4]:
df.dropna(inplace=False) # drop NaN VALUES
df.tail(20)
# df.isnull().sum().sum() 

First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
980   Kimberly  Female   1/26/2013        12:57 AM   46233    8.862   
981      James    Male   1/15/1993         5:19 PM  148985   19.280   
982       Rose  Female    4/6/1982        10:43 AM   91411    8.639   
983       John    Male  12/23/1982        10:35 PM  146907   11.738   
984      Maria  Female  10/15/2011         4:53 PM   43455   13.040   
985    Stephen     NaN   7/10/1983         8:10 PM   85668    1.909   
986      Donna  Female  11/26/1982         7:04 AM   82871   17.999   
987     Gloria  Female   12/8/2014         5:08 AM  136709   10.331   
988      Alice  Female   10/5/2004         9:34 AM   47638   11.209   
989     Justin     NaN   2/10/1991         4:58 PM   38344    3.794   
990      Robin  Female   7/24/1987         1:35 PM  100765   10.982   
991       Rose  Female   8/25/2002         5:12 AM  134505   11.051   
992    Anthony    Male  10/16/2011         8:35 AM  112769   11.625   
993       Tina  Female   5/15/1997         3:53 PM   56450   19.040   
994     George    Male   6/21/2013         5:47 PM   98874    4.479   
995      Henry     NaN  11/23/2014         6:09 AM  132483   16.655   
996    Phillip    Male   1/31/1984         6:30 AM   42392   19.675   
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421   
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985   
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169   

    Senior Management                  Team  
980              True           Engineering  
981             False                 Legal  
982              True       Human Resources  
983             False           Engineering  
984             False           Engineering  
985             False                 Legal  
986             False             Marketing  
987              True               Finance  
988             False       Human Resources  
989             False                 Legal  
990              True       Client Services  
991              True             Marketing  
992              True               Finance  
993              True           Engineering  
994              True             Marketing  
995             False          Distribution  
996             False               Finance  
997             False               Product  
998             False  Business Development  
999              True                 Sales

Fill null values

In [5]:
dff=df.fillna(value=200)
dff
dff1=df.fillna(method='pad')# fill previous value
dff1
dff2=df.fillna(method='bfill')#fil next values
dff2

First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945   
1       Thomas    Male   3/31/1996         6:53 AM   61933    4.170   
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858   
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340   
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389   
..         ...     ...         ...             ...     ...      ...   
995      Henry    Male  11/23/2014         6:09 AM  132483   16.655   
996    Phillip    Male   1/31/1984         6:30 AM   42392   19.675   
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421   
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985   
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169   

     Senior Management                  Team  
0                 True             Marketing  
1                 True               Finance  
2                False               Finance  
3                 True               Finance  
4                 True       Client Services  
..                 ...                   ...  
995              False          Distribution  
996              False               Finance  
997              False               Product  
998              False  Business Development  
999               True                 Sales  

[1000 rows x 8 columns]

In [6]:
dff4=df.fillna({'Team':'Zaheer',
                'Senior Management':333000})# fill diff values in diff columns
dff4.head(20)

First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0     Douglas    Male    8/6/1993        12:42 PM   97308    6.945   
1      Thomas    Male   3/31/1996         6:53 AM   61933    4.170   
2       Maria  Female   4/23/1993        11:17 AM  130590   11.858   
3       Jerry    Male    3/4/2005         1:00 PM  138705    9.340   
4       Larry    Male   1/24/1998         4:47 PM  101004    1.389   
5      Dennis    Male   4/18/1987         1:35 AM  115163   10.125   
6        Ruby  Female   8/17/1987         4:20 PM   65476   10.012   
7         NaN  Female   7/20/2015        10:43 AM   45906   11.598   
8      Angela  Female  11/22/2005         6:29 AM   95570   18.523   
9     Frances  Female    8/8/2002         6:51 AM  139852    7.524   
10     Louise  Female   8/12/1980         9:01 AM   63241   15.132   
11      Julie  Female  10/26/1997         3:19 PM  102508   12.637   
12    Brandon    Male   12/1/1980         1:08 AM  112807   17.492   
13       Gary    Male   1/27/2008        11:40 PM  109831    5.831   
14   Kimberly  Female   1/14/1999         7:13 AM   41426   14.543   
15    Lillian  Female    6/5/2016         6:09 AM   59414    1.256   
16     Jeremy    Male   9/21/2010         5:56 AM   90370    7.369   
17      Shawn    Male   12/7/1986         7:45 PM  111737    6.414   
18      Diana  Female  10/23/1981        10:27 AM  132940   19.082   
19      Donna  Female   7/22/2010         3:48 AM   81014    1.894   

   Senior Management                  Team  
0               True             Marketing  
1               True                Zaheer  
2              False               Finance  
3               True               Finance  
4               True       Client Services  
5              False                 Legal  
6               True               Product  
7             333000               Finance  
8               True           Engineering  
9               True  Business Development  
10              True                Zaheer  
11              True                 Legal  
12              True       Human Resources  
13             False                 Sales  
14              True               Finance  
15             False               Product  
16             False       Human Resources  
17             False               Product  
18             False       Client Services  
19             False               Product

In [7]:
dff5=df.fillna(value = df['Bonus %'].mean()) 
dff5.head(20)

First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0     Douglas    Male    8/6/1993        12:42 PM   97308    6.945   
1      Thomas    Male   3/31/1996         6:53 AM   61933    4.170   
2       Maria  Female   4/23/1993        11:17 AM  130590   11.858   
3       Jerry    Male    3/4/2005         1:00 PM  138705    9.340   
4       Larry    Male   1/24/1998         4:47 PM  101004    1.389   
5      Dennis    Male   4/18/1987         1:35 AM  115163   10.125   
6        Ruby  Female   8/17/1987         4:20 PM   65476   10.012   
7   10.207555  Female   7/20/2015        10:43 AM   45906   11.598   
8      Angela  Female  11/22/2005         6:29 AM   95570   18.523   
9     Frances  Female    8/8/2002         6:51 AM  139852    7.524   
10     Louise  Female   8/12/1980         9:01 AM   63241   15.132   
11      Julie  Female  10/26/1997         3:19 PM  102508   12.637   
12    Brandon    Male   12/1/1980         1:08 AM  112807   17.492   
13       Gary    Male   1/27/2008        11:40 PM  109831    5.831   
14   Kimberly  Female   1/14/1999         7:13 AM   41426   14.543   
15    Lillian  Female    6/5/2016         6:09 AM   59414    1.256   
16     Jeremy    Male   9/21/2010         5:56 AM   90370    7.369   
17      Shawn    Male   12/7/1986         7:45 PM  111737    6.414   
18      Diana  Female  10/23/1981        10:27 AM  132940   19.082   
19      Donna  Female   7/22/2010         3:48 AM   81014    1.894   

   Senior Management                  Team  
0               True             Marketing  
1               True             10.207555  
2              False               Finance  
3               True               Finance  
4               True       Client Services  
5              False                 Legal  
6               True               Product  
7          10.207555               Finance  
8               True           Engineering  
9               True  Business Development  
10              True             10.207555  
11              True                 Legal  
12              True       Human Resources  
13             False                 Sales  
14              True               Finance  
15             False               Product  
16             False       Human Resources  
17             False               Product  
18             False       Client Services  
19             False               Product

In [8]:

dff6=df['Bonus %'] = df['Bonus %'].interpolate(method = 'linear')
dff6

0       6.945
1       4.170
2      11.858
3       9.340
4       1.389
        ...  
995    16.655
996    19.675
997     1.421
998    11.985
999    10.169
Name: Bonus %, Length: 1000, dtype: float64

In [9]:
df.value_counts()
df.nunique()
df['Team'].value_counts()
df['Team'].nunique()

10

ONE HOT  CODING USING PANDAS

In [10]:
df22=pd.get_dummies(df,columns=['Team'])
df22

First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945   
1       Thomas    Male   3/31/1996         6:53 AM   61933    4.170   
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858   
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340   
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389   
..         ...     ...         ...             ...     ...      ...   
995      Henry     NaN  11/23/2014         6:09 AM  132483   16.655   
996    Phillip    Male   1/31/1984         6:30 AM   42392   19.675   
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421   
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985   
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169   

    Senior Management  Team_Business Development  Team_Client Services  \
0                True                          0                     0   
1                True                          0                     0   
2               False                          0                     0   
3                True                          0                     0   
4                True                          0                     1   
..                ...                        ...                   ...   
995             False                          0                     0   
996             False                          0                     0   
997             False                          0                     0   
998             False                          1                     0   
999              True                          0                     0   

     Team_Distribution  Team_Engineering  Team_Finance  Team_Human Resources  \
0                    0                 0             0                     0   
1                    0                 0             0                     0   
2                    0                 0             1                     0   
3                    0                 0             1                     0   
4                    0                 0             0                     0   
..                 ...               ...           ...                   ...   
995                  1                 0             0                     0   
996                  0                 0             1                     0   
997                  0                 0             0                     0   
998                  0                 0             0                     0   
999                  0                 0             0                     0   

     Team_Legal  Team_Marketing  Team_Product  Team_Sales  
0             0               1             0           0  
1             0               0             0           0  
2             0               0             0           0  
3             0               0             0           0  
4             0               0             0           0  
..          ...             ...           ...         ...  
995           0               0             0           0  
996           0               0             0           0  
997           0               0             1           0  
998           0               0             0           0  
999           0               0             0           1  

[1000 rows x 17 columns]

K-1 OHE

In [11]:
df3=pd.get_dummies(df,columns=['Team'],drop_first=True)
df3

First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945   
1       Thomas    Male   3/31/1996         6:53 AM   61933    4.170   
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858   
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340   
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389   
..         ...     ...         ...             ...     ...      ...   
995      Henry     NaN  11/23/2014         6:09 AM  132483   16.655   
996    Phillip    Male   1/31/1984         6:30 AM   42392   19.675   
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421   
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985   
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169   

    Senior Management  Team_Client Services  Team_Distribution  \
0                True                     0                  0   
1                True                     0                  0   
2               False                     0                  0   
3                True                     0                  0   
4                True                     1                  0   
..                ...                   ...                ...   
995             False                     0                  1   
996             False                     0                  0   
997             False                     0                  0   
998             False                     0                  0   
999              True                     0                  0   

     Team_Engineering  Team_Finance  Team_Human Resources  Team_Legal  \
0                   0             0                     0           0   
1                   0             0                     0           0   
2                   0             1                     0           0   
3                   0             1                     0           0   
4                   0             0                     0           0   
..                ...           ...                   ...         ...   
995                 0             0                     0           0   
996                 0             1                     0           0   
997                 0             0                     0           0   
998                 0             0                     0           0   
999                 0             0                     0           0   

     Team_Marketing  Team_Product  Team_Sales  
0                 1             0           0  
1                 0             0           0  
2                 0             0           0  
3                 0             0           0  
4                 0             0           0  
..              ...           ...         ...  
995               0             0           0  
996               0             0           0  
997               0             1           0  
998               0             0           0  
999               0             0           1  

[1000 rows x 16 columns]

OHE USING SCIKT LEARN

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[: , :-1,],test_size=0.2)
X_train
X_test
y_train
y_test


First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
430     Andrea  Female   10/1/2010        11:54 AM   79123   19.422   
123      Helen  Female  11/29/2001         2:30 AM   73789   14.841   
933      Doris  Female    7/5/1993         5:54 PM  141439    3.799   
892    Brandon    Male  10/23/1995        12:04 PM   60263    2.709   
148    Patrick     NaN   7/14/1991         2:24 AM  124488   14.837   
..         ...     ...         ...             ...     ...      ...   
839      Joyce  Female   7/25/2001         6:04 AM   51065   16.807   
385      Debra  Female   1/19/2010         8:48 AM   70492    8.895   
180       Mark    Male   4/12/2008         5:40 PM   57286    5.025   
822    Deborah  Female   2/26/2009        10:17 AM  118043    7.266   
344      Scott    Male   5/12/2009         4:36 AM   58248    3.914   

    Senior Management  
430             False  
123              True  
933             False  
892             False  
148              True  
..                ...  
839             False  
385             False  
180              True  
822              True  
344             False  

[200 rows x 7 columns]

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct=ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1])],remainder= "passthrough")
x = np.array(ct.fit_transform(x))
z = ct.fit_transform(x)
print(x)

NameError: name 'x' is not defined

In [29]:
import pandas as pd 

df = pd.DataFrame({"col1": ["Sun", "Sun", "Moon", "Earth", "Moon", "Venus"]})
print("The original data")
print(df)
print("*" * 80)
df_new = pd.get_dummies(df, columns=["col1"], prefix="Planet")
print("The transform data using get_dummies")
print(df_new)

The original data
    col1
0    Sun
1    Sun
2   Moon
3  Earth
4   Moon
5  Venus
********************************************************************************
          The transform data using get_dummies
   Planet_Earth  Planet_Moon  Planet_Sun  Planet_Venus
0             0            0           1             0
1             0            0           1             0
2             0            1           0             0
3             1            0           0             0
4             0            1           0             0
5             0            0           0             1


In [33]:
ids=[1,2,3,4,5]
countries=['India','UAE','Saudi','Oman','China']

df11=pd.DataFrame(list(zip(ids,countries)),columns=['Id','Country'])
print(df)

z=pd.get_dummies(df.Country,prefix='Countries')
z

   Id Country
0   1   India
1   2     UAE
2   3   Saudi
3   4    Oman
4   5   China


Countries_China  Countries_India  Countries_Oman  Countries_Saudi  \
0                0                1               0                0   
1                0                0               0                0   
2                0                0               0                1   
3                0                0               1                0   
4                1                0               0                0   

   Countries_UAE  
0              0  
1              1  
2              0  
3              0  
4              0

Using Sklearn

In [41]:
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({"col1": ["Sun", "Sun", "Moon", "Earth", "Moon", "Venus"]})
df

y=OneHotEncoder().fit_transform(df).toarray()
print(df)
print(y)

    col1
0    Sun
1    Sun
2   Moon
3  Earth
4   Moon
5  Venus
[[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
